# Spring Boot Application Configuration
spring.application.name=quantity-measurement-app

# JPA / Hibernate Configuration
# Render Database Configuration (Use Environment Variables in Production)
spring.datasource.url=${DATABASE_URL:jdbc:h2:file:./data/quantitymeasurementdb;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DATABASE_USER:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driverClassName=${DATABASE_DRIVER:org.h2.Driver}
spring.jpa.database-platform=${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORS Configuration
app.allowedOrigins=${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:3000,https://quantix-frontend-phi.vercel.app}

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# Logging Configuration
logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG


# Swagger / OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Security Configuration
app.jwtSecret=9a67475df65d61474138e841955c9121731668ee0420794fd31c69c6fc965ed4d791550998f4130097746522c73335c9121
app.jwtExpirationMs=86400000


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email,read:user
